buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }

    ext {
        nav_version = '2.9.6'
        lc_version = "2.9.3"
        room_version = "2.8.0"
        ksp_version = '2.3.6'
        fastAdapter_version = "5.7.0"
    }

    dependencies {
        classpath libs.android.gradle.plugin
        classpath libs.kotlin.gradle.plugin
        classpath "androidx.navigation:navigation-safe-args-gradle-plugin:$nav_version"
        classpath libs.google.services
        classpath libs.firebase.crashlytics.gradle
        classpath "com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:$ksp_version"
        classpath libs.secrets.gradle.plugin
    }
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}